const PhasenData = [
  {
    "Phase": "Initialisierung",
    "Beschreibung": "Die Phase Initialisierung wird unabhängig von der späteren Vorgehensweise in jedem Fall durchgeführt. Sie schafft eine definierte Ausgangslage für eine mögliche Lösungsentstehung und den darauffolgenden Projektabschluss. Sie stellt sicher, dass die gesetzten Ziele mit den Vorgaben der Organisation abgestimmt sind. Die Projektgrundlagen und der Durchführungsauftrag werden erarbeitet. ",
    "Details": " - Auf der Grundlage des Projektinitialisierungsauftrags gibt der Auftraggeber die Ressourcen für die Phase Initialisierung frei. Er beauftragt den Projektleiter mit der Durchführung der Phase Initialisierung.<br> - Die Phase Initialisierung wird aus Projektmanagementsicht stets klassisch abgewickelt. Dennoch können auch agile Werkzeuge zum Einsatz kommen.<br> - Die Studie wird erarbeitet.<br> o Die Arbeiten starten mit einer ersten Standortbestimmung, Zielen und groben Anforderungen.<br> o Die Lösungsvarianten werden erarbeitet. Die Beschreibung der Lösungsvarianten erfolgt so detailliert, dass sie nachvollziehbar und transparent bewertet werden können.<br> o Unter anderem werden auch die Projekt- und Betriebsrisiken ermittelt.<br> o Parallel zur Studie werden die Rechtsgrundlagenanalyse und die Schutzbedarfsanalyse erarbeitet und in die Entscheidung einbezogen.<br> o Zusätzlich wird festgelegt und nachvollziehbar dokumentiert, wie im Rahmen jeder Lösungsvariante weiter vorgegangen wird: entweder klassisch oder agil.<br> o Der Entscheid Weiteres Vorgehen wird getroffen.<br> - Für die allfällige Beschaffung eines Produkts bzw. eines Systems wird parallel zur Studie eine Beschaffungsanalyse durchgeführt.<br> - Das für die Lösungsentstehung passende Szenario wird ausgewählt und bei Bedarf individualisiert.<br> - Auf der Basis der gewählten Variante und des Vorgehens werden der Projektmanagementplan und der Durchführungsauftrag erarbeitet und mit den Strategien, Vorgaben und übergeordneten Zielen der Stammorganisation abgeglichen. Die Stakeholderinteressen werden analysiert und Zielkonflikte bereinigt.<br> - Bei anvisierter agiler Vorgehensweise wird festgelegt, ob der optionale Entscheid Releasefreigabe treffen im Projekt als erforderlich vorgeschrieben ist.<br> - Der Entscheid Durchführungsfreigabe wird getroffen und der Durchführungsauftrag unterschrieben. Die Freigabe erfolgt durch die Stammorganisation und den Auftraggeber.",
    "Phasenende": "Am Ende der Phase Initialisierung wird geprüft, ob es sinnvoll ist, die Fortsetzung des Projekts freizugeben und sofern ja, wird der Entscheid Durchführungsfreigabe getroffen. Mögliche Gründe für eine Beendigung sind fehlende Wirtschaftlichkeit, zu hohe Risiken, keine Realisierbarkeit, rechtliche oder politische Bedenken, fehlende Übereinstimmung mit den Zielen, Strategien und Prioritäten der Organisation."
  },
  {
    "Phase": "Konzept",
    "Beschreibung": "Die in der Phase Initialisierung gewählte Variante wird konkretisiert. Die Ergebnisse werden so detailliert erarbeitet, dass die Projektbeteiligten die Lösung auf einer verlässlichen Grundlage planen, offerieren und realisieren können. ",
    "Details": " - Basierend auf der gewählten Variante sowie der ersten Standortbestimmung aus der Studie werden die Situationsanalysen durchgeführt.<br> - Gestützt auf die Erkenntnisse aus den Situationsanalysen werden die Anforderungen aus der Studie konkretisiert und vervollständigt und neu als Lösungsanforderungen festgelegt.<br> - Bei Organisations- und IT-Projekten oder wenn durch die Lösung Geschäftsabläufe oder -strukturen tangiert werden, sind in jedem Fall die Organisationsanforderungen und anschliessend das Organisationskonzept zu erarbeiten.<br> - Die Lösung wird konzeptionell erarbeitet. Die Machbarkeit, allenfalls nur einzelner Lösungskomponenten, wird z. B. mit Prototypen überprüft.<br> - Zur Vorbereitung der Einführung wird das Einführungskonzept erarbeitet.<br> - Je nach Szenario werden Testkonzept und Migrationskonzept erarbeitet.<br> - In IT-Projekten werden zudem die Lösungsarchitektur und das Betriebskonzept erarbeitet. Der Entscheid Lösungsarchitektur wird getroffen.<br> - Ist eine Lösung zu beschaffen, werden die Ausschreibung durchgeführt, die Angebote bewertet sowie das ausgewählte Produkt oder System beschafft.<br> - Bei Systemen wird das Integrationskonzept erarbeitet.<br> - Der Entscheid über die Freigabe der Realisierung wird getroffen (Entscheid Phasenfreigabe treffen).<br> o Die Projekt- und Betriebsrisiken müssen identifiziert, analysiert und bewertet sein.<br> o Die Realisierbarkeit der Lösungsentstehung muss weiterhin nachgewiesen bzw. bestätigt sein.<br> o Die Ressourcen für die nächste Phase werden aufgrund des konkretisierten Projektmanagementplans und der vorliegenden Angebote freigegeben.",
    "Phasenende": "Am Ende der Phase Konzept wird geprüft, ob es sinnvoll ist, das Projekt zu realisieren. Mögliche Gründe für eine Beendigung sind Unwirtschaftlichkeit, zu hohe Risiken, fehlende Realisierbarkeit, fehlende Übereinstimmung mit den Zielen und Strategien der Organisation."
  },
  {
    "Phase": "Realisierung",
    "Beschreibung": "Das Produkt bzw. das System wird realisiert und getestet. Die nötigen Vorarbeiten werden geleistet, um die Einführungsrisiken zu minimieren. ",
    "Details": " - Das Produkt bzw. das System wird entwickelt oder, sofern es beschafft wurde, parametrisiert bzw. angepasst.<br> - Die Organisation wird umgesetzt.<br> - In IT-Projekten wird das System in die Betriebsinfrastruktur integriert.<br> - Die Vorabnahme wird durchgeführt.<br> - Die Betriebsorganisation wird realisiert und die Dokumentationen erarbeitet.<br> - Die Einführung wird auf der Grundlage des Einführungskonzepts vorbereitet.<br> - Je nach Szenario werden Tests durchgeführt und die Migration vorbereitet.<br> - Der Entscheid über die Freigabe der Einführung wird getroffen (Entscheid Phasenfreigabe treffen). Er basiert auf dem Entscheid Vorabnahme. Die Ressourcen für die nächste Phase werden aufgrund des konkretisierten Projektmanagementplans freigegeben. ",
    "Phasenende": "Am Ende der Phase Realisierung müssen die Einführungsrisiken beurteilt werden und vertretbar sein. Andernfalls kann die Einführung nicht erfolgen."
  },
  {
    "Phase": "Einführung",
    "Beschreibung": "In der Phase Einführung wird der sichere Übergang zum neuen Zustand gewährleistet. Der Betrieb wird aufgenommen. ",
    "Details": " - Die Einführungsmassnahmen wie Anwenderschulung usw. werden durchgeführt.<br> - Je nach Szenario wird eine Migration durchgeführt.<br> - Das Produkt bzw. das System sowie die Organisation werden aktiviert.<br> - Der Betrieb wird aktiviert.<br> - ISDS-Konzept wird überführt.<br> - Während der ersten Betriebszeit zwischen der Betriebsaufnahme und der Abnahme des vollständigen Systems oder Produkts unterstützt das Projekt die Problemanalyse und die Problembehebung (danach beginnt die Gewährleistung und damit der reguläre Betrieb).<br> - Der Entscheid Phasenfreigabe Abschluss wird getroffen. Die Ressourcen für die Phase Abschluss werden aufgrund des nachgeführten Projektmanagementplans freigegeben. ",
    "Phasenende": "Am Ende der Phase Einführung wird nach erfolgreicher Betriebsaufnahme der Entscheid Abnahme getroffen und die Phase wird abgeschlossen."
  },
  {
    "Phase": "Abschluss",
    "Beschreibung": "Die Phase Abschluss bietet eine Struktur für das systematische Herunterfahren eines Projektes. Die Projektdokumentation wird geprüft und je nach Bedarf ergänzt. Der Projektabschluss wird vorbereitet. ",
    "Details": " - Die Phase Abschluss wird aus Projektmanagementsicht stets klassisch abgewickelt. Dennoch können auch agile Werkzeuge zum Einsatz kommen.<br> - Die Ergebnisse werden auf Vollständigkeit geprüft und insbesondere aus formeller Sicht ergänzt.<br> - Die Projektschlussbeurteilung wird geprüft und ggf. genehmigt.<br> - Die Projektorganisation wird aufgelöst. Vor der Auflösung kann geprüft werden, ob Teile der Projektorganisation sinngemäss in die Anwendungsorganisation übernommen werden können.<br> - Die Ergebnisse, Dokumentationen usw. werden an die Stammorganisation z.H. der Anwendungs-, Betriebs- und Wartungsorganisation übergeben. In IT-Projekten betrifft dies beispielsweise auch die Testinfrastruktur samt Testkonzept und die Hilfsmittel.<br> - Die Dokumentation der Projektabwicklung inklusive der Vorgehensergebnisse usw. wird gemäss den Ablagevorschriften der Stammorganisation archiviert.<br> - Das Altsystem wird je nach Szenario ausser Betrieb gesetzt und unter Berücksichtigung der Vorgaben inklusive der alten, nicht mehr benötigten Infrastruktur entfernt, die alten Daten werden archiviert oder vernichtet. ",
    "Phasenende": "Am Ende der Phase Abschluss wird der Projektabschluss durchgeführt. Die Projektschlussbeurteilung wird erarbeitet. Offene Punkte werden an die Stammorganisation sowie an die Anwendungsorganisation übergeben. Das Projekt wird abgeschlossen und die Projektorganisation aufgelöst. "
  },
  {
    "Phase": "Umsetzung",
    "Beschreibung": "Die in der Phase Initialisierung gewählte Variante wird iterativ-inkrementell umgesetzt. Die Projektorganisation wird inklusive Entwicklungsteam etabliert. Die Lösungsanforderungen werden weiter aufgeteilt, verfeinert und konkretisiert. Die Anforderungen werden aktualisiert und priorisiert und nach absteigender Priorität abgearbeitet (entwickelt, realisiert und in Betrieb genommen), wobei die Prioritäten kontinuierlich aktualisiert und den Projekterkenntnissen entsprechend angepasst werden. ",
    "Details": " - Basierend auf der gewählten Variante sowie der Standortbestimmung aus der Studie werden die Situationsanalysen durchgeführt.<br> - Mit den Erkenntnissen aus den Situationsanalysen werden die Anforderungen aus der Studie konkretisiert und vervollständigt und neu als priorisierte initiale Lösungsanforderungen festgelegt.<br> - Werden durch die angestrebte Lösung Geschäftsabläufe oder -strukturen tangiert, sind zwingend die Organisationsanforderungen zu erarbeiten.<br> - Ist eine Lösung zu beschaffen, werden die Ausschreibung durchgeführt, die Angebote bewertet sowie das ausgewählte Produkt oder System beschafft.<br> - Mit jeder Iteration wird ein weiterer Teil der Lösung – das Inkrement – erstellt, das sich mit dem bereits erstellten Umfang der Umsetzungsergebnisse nahtlos verbinden lässt. Iterativ-inkrementelle Durchführung:<br> o Die einzelnen Anforderungen der Lösungsanforderungen werden laufend konkretisiert, verfeinert, vervollständigt und soweit aufgeteilt und priorisiert, dass sie in absteigender Priorität abgearbeitet werden können.<br> o Es wird das Organisationskonzept erarbeitet und die sukzessive entstehende Organisation realisiert und dokumentiert.<br> o Die Projekt-, Betriebs- und Einführungsrisiken werden identifiziert, analysiert, bewertet und beurteilt. Die Realisierbarkeit wird überprüft.<br> o Das Produkt wird entwickelt oder angepasst bzw. das System entwickelt oder parametrisiert.<br> o Begleitend werden die Betriebsorganisation und alle anderen Ergebnisse der restlichen Module sukzessive erarbeitet, realisiert und dokumentiert.<br> o Bei Systemen wird das Integrationskonzept erarbeitet und der Entscheid Lösungsarchitektur getroffen.<br> o Bei Systemen werden Tests konzipiert und durchgeführt, die Migration vorbereitet und durchgeführt und das System in die Betriebsinfrastruktur integriert.<br> o Das Einführungskonzept wird erarbeitet sowie die Vorabnahme, die Einführungsmassnahmen wie Anwenderschulung usw. und die Betriebsaufnahme durchgeführt.<br> o Die Organisation, der betreffende Teil der Lösung (ein oder mehrere Inkremente) sowie der Betrieb werden aktiviert.<br> - Während der ersten Betriebszeit bis zu der Abnahme des Teils der Lösung unterstützt das Projekt die Problemanalyse und die Problembehebung (danach beginnt die Gewährleistung und damit der reguläre Betrieb).<br> - Falls im Projektmanagementplan so festgelegt, wird der Entscheid über die Freigabe des nächsten Release getroffen (Entscheid Releasefreigabe treffen).<br> - Der Entscheid Phasenfreigabe Abschluss wird getroffen. Die Ressourcen für die Phase Abschluss werden aufgrund des nachgeführten Projektmanagementplans freigegeben. ",
    "Phasenende": "Nach abgeschlossener Betriebsaufnahme inklusive der Abnahme des letzten Release werden der agile Teil des Projekts und somit die Phase Umsetzung abgeschlossen und das Entwicklungsteam in der Projektorganisation aufgelöst."
  },
  {
    "Phase": "Realisierungseinheiten",
    "Beschreibung": "Wenn die klassisch abgewickelte Lösungsentstehung eines IT-Vorhabens so komplex wird, dass die Realisierung des ganzen Umfangs fraglich erscheint, oder wenn möglichst schnell erste Ergebnisse für die Nutzung geliefert werden sollen, können die Phasen Realisierung und Einführung in mehreren Realisierungseinheiten abgewickelt werden. ",
    "Details": " - Die Phasen Initialisierung und Konzept werden vollständig durchlaufen. Nach der Phase Konzept können Realisierungseinheiten gestartet werden. Ab diesem Zeitpunkt spielt sich das Projekt in den Phasen und Meilensteinen der jeweiligen Realisierungseinheit ab. Es gibt kein übergeordnetes Phasenmodell.<br> - Die Anzahl der Realisierungseinheiten ist durch HERMES nicht begrenzt, aber die Dauer des Projekts soll nicht unbegrenzt sein. Deshalb werden die Realisierungseinheiten in der Phase Konzept gesamthaft geplant.<br> - Jede Realisierungseinheit umfasst die Phasen Realisierung und Einführung. Jede Realisierungseinheit durchläuft die Entscheidungsaufgaben der Steuerung und Führung.<br> - Der Start einer Realisierungseinheit muss durch die Projektsteuerung freigegeben werden. Dazu muss ein aktualisierter Projektmanagementplan vorliegen.<br> - Realisierungseinheiten werden aus Sicht des Controllings bezüglich Kosten, Terminen und Ergebnissen separat geplant und kontrolliert. Sie bilden eigenständige Kontrolleinheiten. Entsprechend soll das Reporting auf die Realisierungseinheiten ausgerichtet sein.<br> - Sinnvollerweise können am Ende jeder Realisierungseinheit eine Schlussbeurteilung der Realisierungseinheit erstellt und die Erfahrungen dokumentiert und genutzt werden. ",
    "Phasenende": "Vorausgesetzt, dass jede Realisierungseinheit mit einer formellen Phasenfreigabe beendet werden konnte, wird am Ende der letzten Realisierungseinheit über die effektive Freigabe der nächsten Phase Abschluss entschieden. In der Phase Abschluss werden entsprechende Aufgaben und Ergebnissen durchgeführt. Dies umfasst auch die Projektschlussbeurteilung sämtlicher Realisierungseinheiten. "
  }
];